# Generated by Django 4.2 on 2025-12-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CekBMI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('diet', 'Diet'), ('exercise', 'Exercise'), ('lifestyle', 'Lifestyle')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
